spring.application.name=brasa-viva
server.port=8080

logging.level.root=INFO
logging.level.edu.escuelaing.dosw.brasaviva=DEBUG

brasaviva.capacidad-parrilla=8
brasaviva.hora-cierre=22:00
brasaviva.minutos-restriccion-cierre=30
brasaviva.minutos-corte-lento=25
brasaviva.capacidad-parqueadero=20
brasaviva.tarifa-parqueadero-hora=3000

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/brasaviva}
spring.datasource.username=${DB_USER:brasaviva}
spring.datasource.password=${DB_PASSWORD:brasaviva}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true