spring.application.name=brasa-viva
server.port=8080

logging.level.root=INFO
logging.level.edu.escuelaing.dosw.brasaviva=DEBUG

brasaviva.capacidad-parrilla=8
brasaviva.hora-cierre=22:00
brasaviva.minutos-restriccion-cierre=30
brasaviva.minutos-corte-lento=25
brasaviva.capacidad-parqueadero=20
brasaviva.tarifa-parqueadero-hora=3000